apps/characters/urls.py
from django.urls import path
from . import views

app_name = 'characters'

urlpatterns = [
    path('', views.characters, name='characters'),
    path('spiderman/', views.spiderman, name='spiderman'),
]

apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('characters/', views.characters, name='characters'),
    path('spiderman/', views.spiderman, name='spiderman'),
    path('movies/', views.movies, name='movies'),
]

apps/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movies, name='movies'),
    path('black_widow_movie/', views.black_widow_movie, name='black_widow_movie'),
]

marvelapp/marvelapp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

marvelapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('characters/', include('characters.urls', namespace='characters')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('black_widow_movie/', include('movies.urls', namespace='black_widow_movie')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/characters/models.py
from django.db import models

# Create your models here.

apps/movies/models.py
from django.db import models

# Create your models here.

apps/characters/views.py
from django.shortcuts import render

# Create your views here.

def characters(request):
    template_name ='characters/characters.html'
    context = {}
    return render(request, template_name, context)

def spiderman(request):
    template_name ='characters/spiderman.html'
    context = {}
    return render(request, template_name, context)

apps/core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    template_name ='core/home.html'
    context = {}
    return render(request, template_name, context)

def characters(request):
    template_name ='marvelapp/characters/characters.html'
    context = {}
    return render(request, template_name, context)

def spiderman(request):
    template_name ='marvelapp/characters/spiderman.html'
    context = {}
    return render(request, template_name, context)

def movies(request):
    template_name ='marvelapp/movies/movies.html'
    context = {}
    return render(request, template_name, context)

apps/movies/views.py
from django.shortcuts import render

# Create your views here.

def movies(request):
    template_name ='movies/movies.html'
    context = {}
    return render(request, template_name, context)

def black_widow_movie(request):
    template_name ='movies/black_widow_movie.html'
    context = {}
    return render(request, template_name, context)

marvelapp/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    template_name ='core/home.html'
    context = {}
    return render(request, template_name, context)

def characters(request):
    template_name ='marvelapp/characters/characters.html'
    context = {}
    return render(request, template_name, context)

def spiderman(request):
    template_name ='marvelapp/characters/spiderman.html'
    context = {}
    return render(request, template_name, context)

def movies(request):
    template_name ='marvelapp/movies/movies.html'
    context = {}
    return render(request, template_name, context)

def black_widow_movie(request):
    template_name ='marvelapp/movies/black_widow_movie.html'
    context = {}
    return render(request, template_name, context)

apps/templates/marvelapp/characters/spiderman.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="sortcut icon" type="image/png" href="../img/calculadora.png" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../css/style.css">

    <title>Marvel</title>
</head>
<body>
    <div class="navbar">
        <header class="d-flex flex-wrap justify-content-center py-3">
            <a href="../index.html" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                <img src="../imgs/marvel_logo.png" width="100" height="45">
            </a>

            <ul class="nav nav-pills">
                <li class="nav-item"><a href="../index.html" class="navbar-item-active" aria-current="page" class="test">Personagens</a></li>
                <li class="nav-item"><a href="../calculadora.html" class="navbar-item">Outros</a></li>
            </ul>
        </header>
    </div>


    <div class="position-relative overflow-hidden p-5 mb-4 text-center" style="background-image: url('images/spiderman.jpg')">
        <div class="col-md-10 p-lg-5 mx-auto my-5">
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <h1 class="display-6 fw-bolder text-uppercase text-white">"When you can do the things that I can, but you don't, and then the bad things happen..."</h1>
            <p>&nbsp;</p>
        </div>
        <div class="product-device shadow-sm d-none d-md-block"></div>
        <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
      </div>

    <div class="container">
        <div class="p-5 mb-4 bg-light rounded-3">
            <div class="container-fluid py-5">
              <h1 class="display-5 fw-bold">Spider-Man</h1>
              <p class="col-md-8 fs-4">Bitten by a radioactive spider, Peter Parker’s arachnid abilities give him amazing powers he uses to help others, while his personal life continues to offer plenty of obstacles.</p>
            </div>
        </div>
    </div>   


    <div class="container px-4 py-5" id="hanging-icons">
        <h2 class="pb-2 border-bottom">Main features</h2>
        <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
          <div class="col d-flex align-items-start">
            <div class="icon-square bg-light text-dark flex-shrink-0 me-3">
              <svg class="bi" width="1em" height="1em"><use xlink:href="#toggles2"/></svg>
            </div>
            <div>
              <h2>Agility</h2>
              <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
            </div>
          </div>
          <div class="col d-flex align-items-start">
            <div class="icon-square bg-light text-dark flex-shrink-0 me-3">
              <svg class="bi" width="1em" height="1em"><use xlink:href="#cpu-fill"/></svg>
            </div>
            <div>
              <h2>Awareness</h2>
              <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
            </div>
          </div>
          <div class="col d-flex align-items-start">
            <div class="icon-square bg-light text-dark flex-shrink-0 me-3">
              <svg class="bi" width="1em" height="1em"><use xlink:href="#tools"/></svg>
            </div>
            <div>
              <h2>Web Shooters</h2>
              <p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence and probably just keep going until we run out of words.</p>
            </div>
          </div>
        </div>
      </div>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
</body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/marvel_ico.png' %}" />

    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/features.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/footers.css' %}">
    <title>{% block title %}Marvel{% endblock title %}</title>
</head>
<body>

    <!-- INICIO: Bloco do Bootstrap a ser incluido -->
    <div class="navbar">
      <header class="d-flex flex-wrap justify-content-center py-3">
          <a href="{% url 'core:home' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
              <img src="{% static 'img/marvel_logo.png' %}" width="100" height="45">
          </a>

          <ul class="nav nav-pills">
            <li class="nav-item"><a href="{% url 'core:home' %}" class="navbar-item" aria-current="page" class="test">Home</a></li>
            <li class="nav-item"><a href="{% url 'movies:movies' %}" class="navbar-item" aria-current="page" class="test">Filmes</a></li>
            <li class="nav-item"><a href="{% url 'characters:characters' %}" class="navbar-item" aria-current="page" class="test">Personagens</a></li>
          </ul>
      </header>  
    </div>

  {% block body %}
  {% endblock body %}


  <div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
      <p class="col-md-4 mb-0 text-muted">&copy; 2021 Company, Inc</p>
  
      <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      </a>
  
      <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a href="{% url 'core:home' %}" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="{% url 'movies:movies' %}" class="nav-link px-2 text-muted">Filmes</a></li>
        <li class="nav-item"><a href="{% url 'characters:characters' %}" class="nav-link px-2 text-muted">Personagens</a></li>
  
      </ul>
    </footer>
  </div>
    <!-- FIM: Bloco do Bootstrap a ser incluido -->
    
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/characters/characters.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }}
{% endblock title %}

{% block body %}

{% load static %}

<!-- Codigo html especifico desse arquivo -->
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="sortcut icon" type="image/png" href="./img/calculadora.png" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    

    <title>Marvel</title>
</head>
<body>
    <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'img/spiderman2.jpg' %}" width="100%" height="225" class="card-image">

            <div class="card-body">
              <p class="card-title-text">SPIDER-MAN (PETER PARKER)</p>
              <p class="card-text">With amazing spider-like abilities, teenage science whiz Peter Parker fights crime and dreams of becoming an Avenger as Spider-Man.</p>
              <div class="d-flex justify-content-between align-items-center">
                <a href="{% url 'characters:spiderman' %}"><button type="button" class="btn btn-sm btn-outline-secondary">Detalhes</button></a>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
           <img src="{% static 'img/captainAmerica.jpg' %}" width="100%" height="225" class="card-image">

            <div class="card-body">
              <p class="card-title-text">CAPTAIN AMERICA</p>
              <p class="card-text">America's World War II Super-Soldier continues his fight in the present as an Avenger and untiring sentinel of liberty.</p>
              <div class="d-flex justify-content-between align-items-center">
                <button type="button" class="btn btn-sm btn-outline-secondary">Detalhes</button>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'img/ironMan.jpg' %}" width="100%" height="225" class="card-image">

            <div class="card-body">
              <p class="card-title-text">IRON MAN</p>
              <p class="card-text">Genius. Billionaire. Philanthropist. Tony Stark's confidence is only matched by his high-flying abilities as the hero called Iron Man.</p>
              <div class="d-flex justify-content-between align-items-center">
                <button type="button" class="btn btn-sm btn-outline-secondary">Detalhes</button>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'img/wanda.jpg' %}" width="100%" height="225" class="card-image">

            <div class="card-body">
              <p class="card-title-text">WANDA MAXIMOFF</p>
              <p class="card-text">Notably powerful, Wanda Maximoff has fought both against and with the Avengers, attempting to hone her abilities and do what she believes is right to help the world.</p>
              <div class="d-flex justify-content-between align-items-center">
                <button type="button" class="btn btn-sm btn-outline-secondary">Detalhes</button>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'img/wolverine.jpg' %}" width="100%" height="225" class="card-image">

            <div class="card-body">
              <p class="card-title-text">WOLVERINE</p>
              <p class="card-text">A mutant with an unstoppable healing power, adamantium metal claws and no-nonsense attitude makes the man called Logan, one of the most ferocious heroes in the universe.</p>
              <div class="d-flex justify-content-between align-items-center">
                <button type="button" class="btn btn-sm btn-outline-secondary">Detalhes</button>
              </div>
            </div>
          </div>
        </div>

        <div class="col">
          <div class="card shadow-sm">
            <img src="{% static 'img/blackWidow.jpg' %}" width="100%" height="225" class="card-image">

            <div class="card-body">
              <p class="card-title-text">BLACK WIDOW</p>
              <p class="card-text">A deadly assassin is closing in on Natasha Romanoff. Now Natasha must reunite with an unlikely group of spies from her past in order to survive and stop a lethal force from being unleashed on the world.</p>
              <div class="d-flex justify-content-between align-items-center">
                <button type="button" class="btn btn-sm btn-outline-secondary">Detalhes</button>
              </div>
            </div>
          </div>
        </div>
        
      </div>
    </div>
  </div>    
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
</body>
</html>

{% endblock body %}

templates/core/home.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }}
{% endblock title %}

{% block body %}

{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


</head>
<body>
  <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <a href="{% url 'characters:characters' %}">
        <img class="d-block w-100" src="{% static 'img/index_img_slider-1.jpg' %}" alt="First slide">
      </a>
        <div class="carousel-caption d-none d-md-block">
          <h5>Tudo sobre os personagens da Marvel</h5>
        </div>
      </div>
      
      
      <div class="carousel-item">
        <a href="{% url 'movies:movies' %}">
          <img class="d-block w-100" src="{% static 'img/index_img_slider-2.jpg' %}" alt="First slide">
        </a>
        <div class="carousel-caption d-none d-md-block">
          <h5>Tudo sobre os filmes da Marvel</h5>
        </div>
      </div>
      
    </div>
    
    
    <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

</body>
</html>

{% endblock body %}

templates/movies/black_widow_movie.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }}
{% endblock title %}

{% block body %}

{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title>Marvel</title>
</head>
<body>
        <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
        background-size: cover;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <div class="container">
        <div class="p-5 mb-4 bg-light rounded-3">
            <div class="container-fluid py-5">
              <h1 class="display-5 fw-bold">Description</h1>
              <p class="col-md-8 fs-4">Black Widow is a 2021 American superhero film based on Marvel Comics featuring the character of the same name. Produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures, it is the 24th film in the Marvel Cinematic Universe (MCU). The film was directed by Cate Shortland from a screenplay by Eric Pearson, and stars Scarlett Johansson as Natasha Romanoff / Black Widow alongside Florence Pugh, David Harbour, O-T Fagbenle, Olga Kurylenko, William Hurt, Ray Winstone, and Rachel Weisz. Set after the events of Captain America: Civil War (2016), the film sees Romanoff on the run and forced to confront her past.</p>
            </div>
        </div>
    </div>

    <div class="container">
        <h1 class="display-5 fw-bold">Characters that appear in the movie</h1>
    <div class="row">
        <div class="col-lg-4">
          <svg class="bd-placeholder-img" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#ffffff"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text><image href="{% static 'img/blackWidow.jpg' %}" height="140" width="140"/></svg>
          <h2>Black Widow</h2>
          <p><a class="btn btn-secondary" href="{% url 'characters:characters' %}">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-4">
          <svg class="bd-placeholder-img" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#ffffff"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text><image href="{% static 'img/spiderman2.jpg' %}" height="140" width="140"/></svg>
          <h2>Spiderman</h2>
          <p><a class="btn btn-secondary" href="{% url 'characters:spiderman' %}">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-4">
            <svg class="bd-placeholder-img" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#ffffff"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text><image href="{% static 'img/captainAmerica.jpg' %}" height="140" width="140"/></svg>
            <h2>Captain America</h2>
            <p><a class="btn btn-secondary" href="{% url 'characters:characters' %}">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->

      <div class="row">
        <div class="col-lg-4">
            <svg class="bd-placeholder-img" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#ffffff"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text><image href="{% static 'img/ironMan.jpg' %}" height="140" width="140"/></svg>
            <h2>Iron Man</h2>
            <p><a class="btn btn-secondary" href="{% url 'characters:characters' %}">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->

        <div class="col-lg-4">
          <svg class="bd-placeholder-img" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#ffffff"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text><image href="{% static 'img/wanda.jpg' %}" height="140" width="140"/></svg>
          <h2>Wanda</h2>
          <p><a class="btn btn-secondary" href="{% url 'characters:characters' %}">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-4">
            <svg class="bd-placeholder-img" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#ffffff"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text><image href="{% static 'img/wolverine.jpg' %}" height="140" width="140"/></svg>
            <h2>Wolverine</h2>
            <p><a class="btn btn-secondary" href="{% url 'characters:characters' %}">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->

      </div><!-- /.row -->



    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
</body>
</html>

{% endblock body %}